### PR TITLE
Remove PRINS-specific headers from generated C++ code

### PR DESCRIPTION
**Pull request by sigiesec**
This change is [Reviewable](https://reviewable.io/reviews/btc-ag/service-idl/44)

### CODE REVIEW

**Comment by schregger** [comment]
Review status: 22 of 23 files reviewed at latest revision, all discussions resolved.

---

*[com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/IModuleStructureStrategy.java, line 11 at r12](https://reviewable.io/reviews/btc-ag/service-idl/44#-LDkNe0Q5bQTdB-BbWRG:-LDkNe0Q5bQTdB-BbWRH:b-xjphkf) ([raw file](https://github.com/btc-ag/service-idl/blob/c61274256459badeeba104f8b395f476ca580686/com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/IModuleStructureStrategy.java#L11)):*
> ```Java
> public interface IModuleStructureStrategy {
> 
>     IPath getIncludeFilePath(Iterable<ModuleDeclaration> declarations, ProjectType type, String baseName,
> ```

Some documentation (javadoc) would be nice.

---

*[com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/cab/CABModuleStructureStrategy.xtend, line 35 at r12](https://reviewable.io/reviews/btc-ag/service-idl/44#-LDkOzroEnug-iA_wA5c:-LDkOzroEnug-iA_wA5d:bi2ci0b) ([raw file](https://github.com/btc-ag/service-idl/blob/c61274256459badeeba104f8b395f476ca580686/com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/cab/CABModuleStructureStrategy.xtend#L35)):*
> ```Xtend
>             GeneratorUtil.asPath(ParameterBundle.createBuilder(module_stack).with(project_type).build,
>                 ArtifactNature.CPP)).append(if (headerType == HeaderType.PROTOBUF_HEADER) "gen" else "include").append(
>             baseName).addFileExtension(if (headerType == HeaderType.PROTOBUF_HEADER) "pb.h" else "h")
> ```

Such "mega" chains are error-prone and should be split-up. Additionally, it is hard to find out what is actually done.

---

*[com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/prins/PrinsModuleStructureStrategy.xtend, line 32 at r12](https://reviewable.io/reviews/btc-ag/service-idl/44#-LDkQCWz4VBXplWFaoUu:-LDkQCWz4VBXplWFaoUv:bi2ci0b) ([raw file](https://github.com/btc-ag/service-idl/blob/c61274256459badeeba104f8b395f476ca580686/com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/prins/PrinsModuleStructureStrategy.xtend#L32)):*
> ```Xtend
>             GeneratorUtil.asPath(ParameterBundle.createBuilder(module_stack).with(project_type).build,
>                 ArtifactNature.CPP)).append(if (headerType == HeaderType.PROTOBUF_HEADER) "gen" else "include").append(
>             baseName).addFileExtension(if (headerType == HeaderType.PROTOBUF_HEADER) "pb.h" else "h")
> ```

Such "mega" chains are error-prone and should be split-up. Additionally, it is hard to find out what is actually done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/btc-ag/service-idl/44)*

**Comment by schregger** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/btc-ag/service-idl/44)*

**Comment by sigiesec** [comment]
Review status: 19 of 27 files reviewed at latest revision, 3 unresolved discussions.

---

*[com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/IModuleStructureStrategy.java, line 11 at r12](https://reviewable.io/reviews/btc-ag/service-idl/44#-LDkNe0Q5bQTdB-BbWRG:-LDkbjjf85vIGa0_rsLi:b-896fix) ([raw file](https://github.com/btc-ag/service-idl/blob/c61274256459badeeba104f8b395f476ca580686/com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/IModuleStructureStrategy.java#L11)):*
<details><summary><i>Previously, schregger wrote…</i></summary><blockquote>

Some documentation (javadoc) would be nice.
</blockquote></details>

Done.

---

*[com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/cab/CABModuleStructureStrategy.xtend, line 35 at r12](https://reviewable.io/reviews/btc-ag/service-idl/44#-LDkOzroEnug-iA_wA5c:-LDkiDRt44EZYBR_CD1U:bpwjfbl) ([raw file](https://github.com/btc-ag/service-idl/blob/c61274256459badeeba104f8b395f476ca580686/com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/cab/CABModuleStructureStrategy.xtend#L35)):*
<details><summary><i>Previously, schregger wrote…</i></summary><blockquote>

Such "mega" chains are error-prone and should be split-up. Additionally, it is hard to find out what is actually done.
</blockquote></details>

The formatting is unfortunate, but the Xtend formatter cannot be configured to format this in a "stacked" form, unfortunately. The Java code formatter supports this ("Qualified invocations").

A workaround would be to insert trailing line comments, but I do not think this is worthwhile, the indentation is also not really good:

        new Path(ReferenceResolver.MODULES_HEADER_PATH_PREFIX). //
        append(GeneratorUtil.asPath(ParameterBundle.createBuilder(module_stack).with(project_type).build,
            ArtifactNature.CPP)). //
        append(headerType.includeDirectoryName). //
        append(baseName). //
        addFileExtension(headerType.fileExtension)

But I extracted the conditional expressions into functions, which improves readability.

Done.

---

*[com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/prins/PrinsModuleStructureStrategy.xtend, line 32 at r12](https://reviewable.io/reviews/btc-ag/service-idl/44#-LDkQCWz4VBXplWFaoUu:-LDkiCLG0Wtg5cGlXpSx:b-896fix) ([raw file](https://github.com/btc-ag/service-idl/blob/c61274256459badeeba104f8b395f476ca580686/com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/prins/PrinsModuleStructureStrategy.xtend#L32)):*
<details><summary><i>Previously, schregger wrote…</i></summary><blockquote>

Such "mega" chains are error-prone and should be split-up. Additionally, it is hard to find out what is actually done.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/btc-ag/service-idl/44)*

**Comment by schregger** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/btc-ag/service-idl/44)*

**Pull request merged**
