### PR TITLE
Provide a state that has successful .NET integration tests

### PR DESCRIPTION
**Pull request by sigiesec**
This change is [Reviewable](https://reviewable.io/reviews/btc-ag/service-idl/53)

### CODE REVIEW

**Comment by schregger** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/cmdline/CommandLineRunnerTest.xtend, line 77 at r1](https://reviewable.io/reviews/btc-ag/service-idl/53#-LEJ2N7gEuUfM2W165GA:-LEJ2N7gEuUfM2W165GB:bxvfevp) ([raw file](https://github.com/btc-ag/service-idl/blob/13e6f5ea8be131960e625c38719bf3ab5ad78674/com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/cmdline/CommandLineRunnerTest.xtend#L77)):*
> ```Xtend
>         assertEquals(0, Main.mainBackend(Arrays.asList(file.absolutePath, "-outputPath", path.toString)))
>         val files = path.toFile.listFilesRecursively
>         assertEquals(28, files.size)
> ```

Why is this 28? It would be nice to know the reason.

---

*[com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/cmdline/CommandLineRunnerTest.xtend, line 94 at r1](https://reviewable.io/reviews/btc-ag/service-idl/53#-LEJ39VlBjqBe3B3ajGf:-LEJ39VlBjqBe3B3ajGg:bdxr51n) ([raw file](https://github.com/btc-ag/service-idl/blob/13e6f5ea8be131960e625c38719bf3ab5ad78674/com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/cmdline/CommandLineRunnerTest.xtend#L94)):*
> ```Xtend
>     def void testWithImport()
>     {
>         val derivedFile = new File("src/com/btc/serviceidl/tests/testdata/import-derived.idl")
> ```

The path contains a constant part ".../testdata/" which is repeatedly used and should possibly extracted and stored in something like a constant.

---

*[com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/cmdline/CommandLineRunnerTest.xtend, line 101 at r1](https://reviewable.io/reviews/btc-ag/service-idl/53#-LEJ2hiu6_mR7D7Inyrs:-LEJ2hiu6_mR7D7Inyrt:b-qo06h) ([raw file](https://github.com/btc-ag/service-idl/blob/13e6f5ea8be131960e625c38719bf3ab5ad78674/com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/cmdline/CommandLineRunnerTest.xtend#L101)):*
> ```Xtend
>                 Arrays.asList(derivedFile.absolutePath, importedFile.absolutePath, "-outputPath", path.toString)))
>         val files = path.toFile.listFilesRecursively.toList
>         assertEquals(54, files.size)
> ```

Why is this 54?

---

*[com.btc.serviceidl/src/com/btc/serviceidl/generator/dotnet/CSProjGenerator.xtend, line 26 at r1](https://reviewable.io/reviews/btc-ag/service-idl/53#-LEJ4joRDiHvbT-SP2Xp:-LEJ4joRDiHvbT-SP2Xq:b-qp4v5m) ([raw file](https://github.com/btc-ag/service-idl/blob/13e6f5ea8be131960e625c38719bf3ab5ad78674/com.btc.serviceidl/src/com/btc/serviceidl/generator/dotnet/CSProjGenerator.xtend#L26)):*
> ```Xtend
>       // Please do NOT edit line indents in the code below (even though they
>       // may look misplaced) unless you are fully aware of what you are doing!!!
>       // Those indents (2 whitespaces) follow the Visual Studio 2012 standard formatting!!!
> ```

And what is the problem in violating this standard (would be nice to know too)?

---

*[com.btc.serviceidl/src/com/btc/serviceidl/generator/dotnet/NuGetPackageResolver.xtend, line 24 at r1](https://reviewable.io/reviews/btc-ag/service-idl/53#-LEJ5ktJD-RmlBaYHC6M:-LEJ5ktK3KOUj3xN0eVZ:bk340fz) ([raw file](https://github.com/btc-ag/service-idl/blob/13e6f5ea8be131960e625c38719bf3ab5ad78674/com.btc.serviceidl/src/com/btc/serviceidl/generator/dotnet/NuGetPackageResolver.xtend#L24)):*
> ```Xtend
>     // ******************************* PLEASE ALWAYS KEEP THIS LIST ALPHABETICALLY SORTED !!! ******************************* //
>     static val version_mapper = #{
>         "BTC.CAB.Commons" -> "1.8.7",
> ```

Could this be something like 1.8.* or 1.8.latest. I guess the minor version is not really relevant? No issue, only wondering.

---


*Comments from [Reviewable](https://reviewable.io/reviews/btc-ag/service-idl/53)*

**Comment by huttenlocher** [comment]
*[com.btc.serviceidl/src/com/btc/serviceidl/generator/dotnet/CSProjGenerator.xtend, line 26 at r1](https://reviewable.io/reviews/btc-ag/service-idl/53#-LEJ4joRDiHvbT-SP2Xp:-LEJ8Y2b6RWsOUMgr_e2:b-pns44o) ([raw file](https://github.com/btc-ag/service-idl/blob/13e6f5ea8be131960e625c38719bf3ab5ad78674/com.btc.serviceidl/src/com/btc/serviceidl/generator/dotnet/CSProjGenerator.xtend#L26)):*
<details><summary><i>Previously, schregger wrote…</i></summary><blockquote>

And what is the problem in violating this standard (would be nice to know too)?
</blockquote></details>

The problem is that at some point of time (new file added, new project reference added, etc.) the Studio might reformat the whole file and you will see a huge delta in the diff tool while in fact there is only one line has been changed. As simple as this.

---


*Comments from [Reviewable](https://reviewable.io/reviews/btc-ag/service-idl/53)*

**Comment by sigiesec** [comment]
*[com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/cmdline/CommandLineRunnerTest.xtend, line 77 at r1](https://reviewable.io/reviews/btc-ag/service-idl/53#-LEJ2N7gEuUfM2W165GA:-LELeTBJBaVigpJ73dAl:b86gxy7) ([raw file](https://github.com/btc-ag/service-idl/blob/13e6f5ea8be131960e625c38719bf3ab5ad78674/com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/cmdline/CommandLineRunnerTest.xtend#L77)):*
<details><summary><i>Previously, schregger wrote…</i></summary><blockquote>

Why is this 28? It would be nice to know the reason.
</blockquote></details>

This (and several other tests) is a kind of regression test at the moment. It should probably evolve into a more direct test explicitly testing the expected files.

---


*Comments from [Reviewable](https://reviewable.io/reviews/btc-ag/service-idl/53)*

**Comment by sigiesec** [comment]
*[com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/cmdline/CommandLineRunnerTest.xtend, line 94 at r1](https://reviewable.io/reviews/btc-ag/service-idl/53#-LEJ39VlBjqBe3B3ajGf:-LELeuN322A4SUj-n5oc:bebrt1w) ([raw file](https://github.com/btc-ag/service-idl/blob/13e6f5ea8be131960e625c38719bf3ab5ad78674/com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/cmdline/CommandLineRunnerTest.xtend#L94)):*
<details><summary><i>Previously, schregger wrote…</i></summary><blockquote>

The path contains a constant part ".../testdata/" which is repeatedly used and should possibly extracted and stored in something like a constant.
</blockquote></details>

Will do

---


*Comments from [Reviewable](https://reviewable.io/reviews/btc-ag/service-idl/53)*

**Comment by sigiesec** [comment]
*[com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/cmdline/CommandLineRunnerTest.xtend, line 101 at r1](https://reviewable.io/reviews/btc-ag/service-idl/53#-LEJ2hiu6_mR7D7Inyrs:-LELeywm7fpy2pWquXKV:b-pl8pxf) ([raw file](https://github.com/btc-ag/service-idl/blob/13e6f5ea8be131960e625c38719bf3ab5ad78674/com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/cmdline/CommandLineRunnerTest.xtend#L101)):*
<details><summary><i>Previously, schregger wrote…</i></summary><blockquote>

Why is this 54?
</blockquote></details>

See other comment

---


*Comments from [Reviewable](https://reviewable.io/reviews/btc-ag/service-idl/53)*

**Comment by sigiesec** [comment]
*[com.btc.serviceidl/src/com/btc/serviceidl/generator/dotnet/NuGetPackageResolver.xtend, line 24 at r1](https://reviewable.io/reviews/btc-ag/service-idl/53#-LEJ5ktJD-RmlBaYHC6M:-LELfCQ10TdbxBrnLVaI:b-3vd3ma) ([raw file](https://github.com/btc-ag/service-idl/blob/13e6f5ea8be131960e625c38719bf3ab5ad78674/com.btc.serviceidl/src/com/btc/serviceidl/generator/dotnet/NuGetPackageResolver.xtend#L24)):*
<details><summary><i>Previously, schregger wrote…</i></summary><blockquote>

Could this be something like 1.8.* or 1.8.latest. I guess the minor version is not really relevant? No issue, only wondering.
</blockquote></details>

@huttenlocher Did you do it this way for a reason?

---


*Comments from [Reviewable](https://reviewable.io/reviews/btc-ag/service-idl/53)*

**Comment by huttenlocher** [comment]
*[com.btc.serviceidl/src/com/btc/serviceidl/generator/dotnet/NuGetPackageResolver.xtend, line 24 at r1](https://reviewable.io/reviews/btc-ag/service-idl/53#-LEJ5ktJD-RmlBaYHC6M:-LEO77090lFeOHcbjFZP:b50f5f3) ([raw file](https://github.com/btc-ag/service-idl/blob/13e6f5ea8be131960e625c38719bf3ab5ad78674/com.btc.serviceidl/src/com/btc/serviceidl/generator/dotnet/NuGetPackageResolver.xtend#L24)):*
<details><summary><i>Previously, sigiesec (Simon Giesecke) wrote…</i></summary><blockquote>

@huttenlocher Did you do it this way for a reason?
</blockquote></details>

@sigiesec, in the original version only `Google.ProtocolBuffers` and `CommandLineParser` has been retrieved this way. I 'm not sure, that I could use "latest" in that case (`Install-Package Google.ProtocolBuffers -Version 2.4.1.555` works, but `Install-Package Google.ProtocolBuffers -Version 2.4.latest` fails). I do not know all the nuances of NuGet, so I used only what was sufficient for our purpose.

---


*Comments from [Reviewable](https://reviewable.io/reviews/btc-ag/service-idl/53)*

**Comment by sigiesec** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/cmdline/CommandLineRunnerTest.xtend, line 77 at r1](https://reviewable.io/reviews/btc-ag/service-idl/53#-LEJ2N7gEuUfM2W165GA:-LEPIp936KzeAmytyXTl:b-896fix) ([raw file](https://github.com/btc-ag/service-idl/blob/13e6f5ea8be131960e625c38719bf3ab5ad78674/com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/cmdline/CommandLineRunnerTest.xtend#L77)):*
<details><summary><i>Previously, sigiesec (Simon Giesecke) wrote…</i></summary><blockquote>

This (and several other tests) is a kind of regression test at the moment. It should probably evolve into a more direct test explicitly testing the expected files.
</blockquote></details>

Done.

---

*[com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/cmdline/CommandLineRunnerTest.xtend, line 94 at r1](https://reviewable.io/reviews/btc-ag/service-idl/53#-LEJ39VlBjqBe3B3ajGf:-LEPJTM8Bgdo84fJ92zj:b-896fix) ([raw file](https://github.com/btc-ag/service-idl/blob/13e6f5ea8be131960e625c38719bf3ab5ad78674/com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/cmdline/CommandLineRunnerTest.xtend#L94)):*
<details><summary><i>Previously, sigiesec (Simon Giesecke) wrote…</i></summary><blockquote>

Will do
</blockquote></details>

Done.

---

*[com.btc.serviceidl/src/com/btc/serviceidl/generator/dotnet/NuGetPackageResolver.xtend, line 24 at r1](https://reviewable.io/reviews/btc-ag/service-idl/53#-LEJ5ktJD-RmlBaYHC6M:-LEPJWL79_PJCK2DTyaw:b-1q2e7x) ([raw file](https://github.com/btc-ag/service-idl/blob/13e6f5ea8be131960e625c38719bf3ab5ad78674/com.btc.serviceidl/src/com/btc/serviceidl/generator/dotnet/NuGetPackageResolver.xtend#L24)):*
<details><summary><i>Previously, huttenlocher (Anton Huttenlocher) wrote…</i></summary><blockquote>

@sigiesec, in the original version only `Google.ProtocolBuffers` and `CommandLineParser` has been retrieved this way. I 'm not sure, that I could use "latest" in that case (`Install-Package Google.ProtocolBuffers -Version 2.4.1.555` works, but `Install-Package Google.ProtocolBuffers -Version 2.4.latest` fails). I do not know all the nuances of NuGet, so I used only what was sufficient for our purpose.
</blockquote></details>

Ok, I will add a comment for now to look at this at some point in the future.

---


*Comments from [Reviewable](https://reviewable.io/reviews/btc-ag/service-idl/53)*

**Pull request merged**
