### PR TITLE
Allow multiple input files to be specified on the command line, and

### PR DESCRIPTION
**Pull request by sigiesec**
imports to be resolved.

---
This change is [Reviewable](https://reviewable.io/reviews/btc-ag/service-idl/41)

### CODE REVIEW

**Comment by schregger** [comment]
*[com.btc.serviceidl/src/com/btc/serviceidl/generator/Main.java, line 54 at r1](https://reviewable.io/reviews/btc-ag/service-idl/41#-LCXUTonEJamXhyYCMl6:-LCXUToo47tYf99_Gv9I:b-2jbhk1) ([raw file](https://github.com/btc-ag/service-idl/blob/705a7fcbfffc3adebdd995eb3c4de63f2e47ed2d/com.btc.serviceidl/src/com/btc/serviceidl/generator/Main.java#L54)):*
> ```Java
>             new HelpFormatter().printHelp("Generator", createOptions());
>             System.err.println("Aborting: no path to EMF resource provided!");
>             return 2;
> ```

Is there a way to give the returns a name like with an enum?

---


*Comments from [Reviewable](https://reviewable.io/reviews/btc-ag/service-idl/41)*

**Comment by schregger** [comment]
*[com.btc.serviceidl/src/com/btc/serviceidl/generator/Main.java, line 96 at r1](https://reviewable.io/reviews/btc-ag/service-idl/41#-LCXUptN9xoKJMpW-rE3:-LCXUptN9xoKJMpW-rE4:bctmbl0) ([raw file](https://github.com/btc-ag/service-idl/blob/705a7fcbfffc3adebdd995eb3c4de63f2e47ed2d/com.btc.serviceidl/src/com/btc/serviceidl/generator/Main.java#L96)):*
> ```Java
>     private JavaIoFileSystemAccess fileAccess;
> 
>     private boolean runGenerator(String[] inputFiles, String outputPath) {
> ```

The naming is not optimal because the return is not shown. Maybe use 'runGeneratorWithoutError(...)'. Then: if (runGeneratorWithoutError)  /* good case */ else /* bad case */

---


*Comments from [Reviewable](https://reviewable.io/reviews/btc-ag/service-idl/41)*

**Comment by schregger** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/btc-ag/service-idl/41)*

**Comment by sigiesec** [comment]
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[com.btc.serviceidl/src/com/btc/serviceidl/generator/Main.java, line 54 at r1](https://reviewable.io/reviews/btc-ag/service-idl/41#-LCXUTonEJamXhyYCMl6:-LDfJQFVDF49XEFaa_bl:b-896fix) ([raw file](https://github.com/btc-ag/service-idl/blob/705a7fcbfffc3adebdd995eb3c4de63f2e47ed2d/com.btc.serviceidl/src/com/btc/serviceidl/generator/Main.java#L54)):*
<details><summary><i>Previously, sigiesec (Simon Giesecke) wrote…</i></summary><blockquote>

An enum cannot be used here, but named constants can be introduced.
</blockquote></details>

Done.

---

*[com.btc.serviceidl/src/com/btc/serviceidl/generator/Main.java, line 96 at r1](https://reviewable.io/reviews/btc-ag/service-idl/41#-LCXUptN9xoKJMpW-rE3:-LDfJP1p8NRm2YZ_PLgP:b-896fix) ([raw file](https://github.com/btc-ag/service-idl/blob/705a7fcbfffc3adebdd995eb3c4de63f2e47ed2d/com.btc.serviceidl/src/com/btc/serviceidl/generator/Main.java#L96)):*
<details><summary><i>Previously, sigiesec (Simon Giesecke) wrote…</i></summary><blockquote>

I think the naming conventions would state tryRunGenerator
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/btc-ag/service-idl/41)*

**Comment by schregger** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/btc-ag/service-idl/41)*

**Pull request merged**
